# Lists
Up until now, we have been storing data in variables.  A limitation of this is that we can only store one value in a variable.  There are many cases in which we need to store multiple values.  For example, the names of all students in a class.  We could create a variable for each student, but that would be very restrictive.  We would also need to know the number of students we have before we begin.

A better way to store multiple values is to use a list.  A list is a collection of values that can be of any type.  Lists allow us to store multiple values in a single variable.  We can then access those variables individually using an index.  This can be visualised as a table, where each row is a value in the list and the columns are the indices.

<b><span style="color: darkblue; font-size:16px;">names =</span></b>

<table style="margin-left: 0; border-collapse: collapse; width: 50%; font-size: 14px;">
    <tr>
        <th style="text-align: left;"><b>0</b></th>
        <th style="text-align: left;"><b>1</b></th>
        <th style="text-align: left;"><b>2</b></th>
        <th style="text-align: left;"><b>3</b></th>
    </tr>
    <tr>
        <td> Bob</td>
        <td>Alice</td>
        <td>Charlie</td>
        <td>David</td>
    </tr>
</table>

In the above example, our variable is `names` and it contains a list of four names.  Each name is stored at an index, which is a number that represents its position in the list.  The first name is at index 0, the second name is at index 1, and so on.  

Notice that the index starts at 0, not 1.  This is a common convention in programming languages, and it is important to remember when working with lists.

*what name is at index 2?*
*what is the size of the list?  What is the last index?*

We can store all types of data in a list.  We could store a list of student test scores as integers.



<b><span style="color: darkblue; font-size:16px;">scores =</span></b>
<table style="margin-left: 0; border-collapse: collapse; width: 50%; font-size: 14px;">
    <tr>
        <th style="text-align: left;"><b>0</b></th>
        <th style="text-align: left;"><b>1</b></th>
        <th style="text-align: left;"><b>2</b></th>
        <th style="text-align: left;"><b>3</b></th>
    </tr>
    <tr>
        <td> 90</td>
        <td>85</td>
        <td>78</td>
        <td>92</td>
    </tr>
</table>


Python lists allow us to store values of different types.  For example, we can store a string, an integer, and a float in the same list.  Many programming languages do not allow this, but Python does. 


We can create a list by enclosing the values in `square brackets` and separating them with `commas`.  For example, we can create a list of students as follows:
```python
names = ['Bob', 'Alice', 'Charlie', 'David']
scores = [90, 85, 78, 92]
```

We can access each individual value in the list using its index.  For example, to access the first name in the list, we can use the following code:
```python
print(names[0])
```
This will print `Bob`, which is the first name in the list.  We can also use this syntax to change the value of a specific index in the list.  For example, to change the first name in the list to `Eve`, we can use the following code:
```python
names[0] = 'Eve'
print(names[0])
```
This replaces `Bob` with `Eve` in the list.  

### Mini Task
1. Create a list of your five favourite foods.
2. Print the first food in the list.
3. Change the first food in the list to your least favourite food.
4. Print the last food in the list.

In [ ]:
# Mini Task
#1



#2


#3



#4

# Lists are dynamic
Python lists are dynamic, which means that we can change their size.  We can add or remove values from the list at any time.  For example, we can add a new name to the list of students as follows:
```python
names.append('Eve')
print(names)
```
This will add `Eve` to the end of the list.  We can also remove a name from the list using the `remove` method.  For example, to remove `Alice` from the list, we can use the following code:
```python
names.remove('Alice')
print(names)
```

We can also remove a name from the list using the `pop` method.  This method removes the last value in the list and returns it.  For example, to remove the last name in the list, we can use the following code:
```python
names.pop()
print(names)
```

This will remove `David` from the list and return it.  We can also specify an index to remove a specific value from the list.  For example, to remove the first name in the list, we can use the following code:
```python
names.pop(0)
print(names)
```
This will remove `Bob` from the list and return it.  We can also use the `insert` method to add a value at a specific index in the list.

# Mini Task
1. Create a list of your three favourite movies.
2. Print the list.
3. Add a new movie to the end of the list.
4. Print the list.
5. Remove the second movie from the list.
6. Print the list.
7. Add a new movie to the end of the list.
8. Print the list.
9. Remove the least favourite movie from the list by its name.
10. Print the list.

In [ ]:
#Mini Task

#1

#2

#3

#4

#5

#6

#7

#8

#9

#10

## Lists and Loops - A perfect match
Lists and loops are a perfect match.  We can use a loop to iterate over each value in the list and perform an action on it.  Lists conveniently have indexes that increase by 1.  That's fairly familiar in the context of loops.  We have made plenty of counters.  We can use the counter as an index to access each value in the list.
```python
names = ['Bob', 'Alice', 'Charlie', 'David']
counter = 0
while counter < len(names):
    print(names[counter])
    counter += 1
```
This will print each name in the list on a new line.  `len(names)` returns the size of the list, which is 4 in this case.
*What is the value of `counter` after the loop?*
*What is the value of `names[counter]` after the loop?*

### Mini Task
From the array provided below:
1.  Print all values
2.  Print all values in reverse order
3.  Add 2 to each value
4.  Print the new list

In [ ]:
# Mini Task
temps = [11, 18, 34, 22, 15, 28, 30, 25, 19, 12]

# code here

## For - another type of loop
`for` loops are another type of loop that is commonly used in programming.  They are often used to iterate over a list or a range of numbers.  The syntax for a `for` loop is as follows:
```python
for variable in list:
    # do something with variable
```

The equivalent `for` loop for the previous example would be:
```python
names = ['Bob', 'Alice', 'Charlie', 'David']
for name in names:
    print(name)
```
The `for` loop automatically handles the counter for us, so we don't need to create one ourselves.  This makes the code cleaner and easier to read.  

The `for` loop will iterate over each value in the list and assign it to the variable `name`.  We can then use this variable to perform an action on each value in the list.

We could for example add a surname of 'Smith' to each name in the list.

```python
names = ['Bob', 'Alice', 'Charlie', 'David']
for name in names:
    print(name + ' Smith')
```

`for` loops are a great way to iterate over lists as we don't need to worry about the counter and thus stuck in an infinite loop.  We can also use the `range` function to create a list of numbers to iterate over.  For example, to print the numbers from 0 to 9, we can use the following code:
```python
for i in range(10):
    print(i)
```

If we wish to access the iterator value, we can use the variable `i` in the loop.  This is similar to using a counter in a `while` loop. The syntax is a little tricky...
```python
names = ['Bob', 'Alice', 'Charlie', 'David']
for i, name in enumerate(names):
    print(i, ': ', name)
```
Here `i` is the index, `name` is the local variable that holds the value of the current iteration.  We then use `enumerate` on the list to get the value and the index at the same time.  This is a very useful function that we will use often. 

### Mini Task
Use a `for` loop for the below.
From the array provided below:
1.  Print all values
3.  Add 2 to each value
4.  Print the new list

In [ ]:
# mini task
temps = [11, 18, 34, 22, 15, 28, 30, 25, 19, 12]

# code here

## Tuples
Tuples are similar to lists, but they are *immutable*.  This means that once we create a tuple, we cannot change its values.  Tuples are created using parentheses instead of square brackets.  For example, we can create a tuple of students as follows:
```python
students = ('Bob', 'Alice', 'Charlie', 'David')
```
We can access the values in a tuple using the same syntax as lists.  For example, to access the first student in the tuple, we can use the following code:
```python
print(students[0])
```
This will print `Bob`, which is the first student in the tuple.  We can also use the `len` function to get the size of the tuple.  For example, to get the size of the tuple, we can use the following code:
```python
print(len(students))
```
This will print `4`, which is the size of the tuple.  We can also use the `in` operator to check if a value is in the tuple.  For example, to check if `Alice` is in the tuple, we can use the following code:
```python
print('Alice' in students)
```

Tuples are often used to store values that have a relation to one another.  For example, we can use a tuple to store the coordinates of a point in 2D space.  We can create a tuple of coordinates as follows:
```python
coordinates = (3, 4)
```
We can then access the x and y coordinates using the following code:
```python
print(coordinates[0])
print(coordinates[1])
```

Another example is storing a student's name and score:
```python
student = ('Bob', 90)
print(student[0])
print(student[1])
```

We can combine tuples and lists.  For example, we can create a list of tuples to store the names and scores of students as follows:
```python
students = [('Bob', 90), ('Alice', 85), ('Charlie', 78), ('David', 92)]
```

Lets add in `for` loops to iterate over the list of tuples.  We can use the following code:
```python
students = [('Bob', 90), ('Alice', 85), ('Charlie', 78), ('David', 92)]
for student in students:
    print(student[0], ': ', str(student[1]))
```
This will print each student's name and score on a new line.  We can also use the `enumerate` function to get the index of each student in the list.  For example, to print the index and name of each student, we can use the following code:
```python
students = [('Bob', 90), ('Alice', 85), ('Charlie', 78), ('David', 92)]
for i, student in enumerate(students):
    print(str(i), ': ', student[0] ' - ', student[1])
```

### Mini Task
Create a list of tuples to store the table below:

<table style="margin-left: 0; border-collapse: collapse; width: 15%; font-size: 14px;">
    <tr style="background-color: #13BDE3;">
       <th style="text-align: left;"><b>Rego</b></th>
        <th style="text-align: left;"><b>Year</b></th>
    </tr>
    <tr>
        <td>ABC123</td>
        <td>2023  </td>
    </tr>
    <tr>
        <td>MNH678</td>
        <td>2022 </td>
    </tr>
    <tr>
        <td> UYW101t</td>
        <td> 2021  </td>
    </tr>
    <tr>
        <td>TSF121</td>
        <td>2020 </td>
    </tr>
</table>

Then:
1.  Print the list of tuples.
2.  Print the first tuple.
3.  Add another tuple to the list GPF543

In [ ]:
# Mini Task

## Dictionaries
Dictionaries are another type of data structure that is used to store key-value pairs.  A dictionary is similar to a list, but instead of using an index to access the values, we use a **key**.  
A key is a unique identifier for each value in the dictionary.  For example, we can create a dictionary of a student with ther name, id, age and score as follows:
```python
student = {
    'Name': 'Bob',
    'Id': 90988424,
    'Age': 30,
    'Score': 78,
}
```

We can access the values in the dictionary using the key.  For example, to access the name of the student, we can use the following code:
```python
print(student['Name'])
```
This will print `Bob`, which is the name of the student.

In another example, we can create a dictionary of students and their id as follows:
```python
students = {
    'Bob': 90988424,
    'Alice': 8543423,
    'Charlie': 7878978,
    'David': 9256747,
}
```
This way we can access the id of each student using their name as the key.  For example, to access the id of `Alice`, we can use the following code:
```python
print(students['Alice'])
```

### Mini Task
1. Create a dictionary of your five favourite foods and their prices.
2. Print the dictionary.
3. Print the price of the first food in the dictionary.

### Mini Task 2
1. Create a list of dictionaries to store the table below:
<table style="margin-left: 0; border-collapse: collapse; width: 15%; font-size: 14px;">
    <tr style="background-color: #13BDE3;">
       <th style="text-align: left;"><b>Rego</b></th>
        <th style="text-align: left;"><b>Year</b></th>
    </tr>
    <tr>
        <td>ABC123</td>
        <td>2023  </td>
    </tr>
    <tr>
        <td>MNH678</td>
        <td>2022 </td>
    </tr>
    <tr>
        <td> UYW101t</td>
        <td> 2021  </td>
    </tr>
    <tr>
        <td>TSF121</td>
        <td>2020 </td>
    </tr>
</table>
2. Print the list of dictionaries.
3. Print the first dictionary.
4. Add another dictionary to the list GPF543
5. Print the list of dictionaries.
6. Print the Year of the last dictionary.
7. Print the Rego of the first dictionary.

In [ ]:
# Mini Task


# Mini Task 2